[package]
name = "n0-qlog"
version = "0.1.0"
description = "qlog data model for QUIC and HTTP/3"
repository = "https://github.com/n0-computer/n0-qlog.git"
authors = ["n0 team <hello@n0.computer>", "Lucas Pardue <lucas@lucaspardue.com>"]
edition = "2021"
rust-version = "1.82"
license = "BSD-2-Clause"
keywords = ["quic", "http3", "qlog"]
categories = ["network-programming"]
readme = "README.md"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_with = { version = "3.3", default-features = false, features = ["macros"] }
smallvec = { version = "1.10", default-features = false, features = ["serde"] }
strum = { version = "0.27.2", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.4"
